### ISSUE TITLE
SparseSync怎么用来打分同步性的

### ISSUE THREAD

**Issue by laodar** [zwx8981/ADTH-QA#2]
是用预训练好的吗

**Comment by zwx8981** [comment]
@laodar 是的，用官方预训练好的

**Comment by laodar** [comment]
> @laodar 是的，用官方预训练好的

@zwx8981 好的多谢。但是那个模型输出的不是偏移量吗，偏移量越大越不同步吗？为啥效果比用SyncNet的更好呢

**Comment by zwx8981** [comment]
@laodar 是的，偏移量越大同步性越差。比SyncNet更好是因为SparseSync的判断与我们在主观实验中收集到的人类偏好数据一致ing更高，即论文中提及的 2AFC score更高。
